[package]
name = "px-common"
version = "0.0.9-devel"
authors = ["Skarlett <zykl@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "px_common"

[dependencies]
