[package]
name = "port_scanner"
version = "0.0.10-devel"
authors = ["Skarlett <zykl@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies.tokio]
version = "1.2"
features = [
    "parking_lot",
    "net",
    "time",
    "rt-multi-thread",
    "rt",
    "sync",
    "time",
    "fs",
    "tracing",
    "test-util"
]

[dependencies.tokio-stream]
version = "0.1.3"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.smallvec]
version = "1.6"
features = ["serde"]

[dependencies]
px-core = { path = "../../crates/px-core" }

async-trait = "0.1"
cidr-utils = "0.5"
structopt = "0.3"
serde_json = "1.0"
num_cpus = "1.13"

# Dependency conflict patches
syn = "^1.0.33"
