[package]
name = "nmap-service-probes-linter"
version = "0.0.10-devel"
authors = ["Skarlett <zykl@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "fs", "io-util", "io-std" ]}
structopt = "*"
px-nmap = { path = "../../crates/px-nmap" }